apiVersion: apps/v1
kind: Deployment
metadata:
  name: omerapp
spec:
  selector:
    matchLabels:
      app: omerapp
  replicas: 2
  template:
    metadata:
      labels:
        app: omerapp
    spec:
      containers:
      - name: omerapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
